#+title: Dotfile
This is mainly for my own convenience when it comes to setting up a new machine. Feel free to use anything you'd like from here.

I run emacs as my desktop enviornment, if you want to replicate it, it's easiest if you get emacs as well. There's a script that builds one from source with flags suitable for my needs.

The OS I'm using as base is Debian 12. Reason behind it is stability - I never want my environment to break unless I explicitly break it myself. No update should cause me loss of productivity or extra work just to make my computer usable again. It probably works out of the box on other debian-based distributions, such as ubuntu as well, but I haven't bothered to try. Debian stable's apt repo has an ancient version of emacs (and it's probably not built the way I want anyway), so, I simply build my own.

* Core components
- emacs
- xmodmap
- linux
- xorg

I'll do my best to keep the generic components separate from highly opinionated and very optional components. This is for my own convenience, as I don't use SDR things, gaming etc on every computer I have, so the base setup does not include such things.
File names start with a number, this is the step order. If it's immediately followed by =-asroot=, such as =1-asroot-base-deps.sh=, it means it should be run as root. Otherwise it should be run as the user.

You may want to edit root-tangle.org in the LXDM section, if you want to log in to emacs automatically.

* Base dependencies
Installs various things needed to build emacs, and use it as my window manager.
#+begin_src shell :tangle ./1-asroot-base-deps.sh
  apt install -y git wget xorg xz-utils build-essential unclutter flameshot xsettingsd

  # some fonts and a theme
  apt install -y fonts-liberation2 fonts-dejavu materia-gtk-theme

  # for emacs build
  apt install -y xorg-dev libjansson-dev libtree-sitter-dev libmagickwand-dev libgtk-3-dev libwebkit2gtk-4.0-dev libgnutls28-dev libsystemd-dev libgif-dev libncurses-dev texinfo libgccjit-12-dev libm17n-dev libotf-dev libxft-dev

  # login manager & gui app root access
  apt install -y lxpolkit lxdm

  # for firefox
  wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null
  gpg -n -q --import --import-options import-show /etc/apt/keyrings/packages.mozilla.org.asc | awk '/pub/{getline; gsub(/^ +| +$/,""); print "\n"$0"\n"}'
  echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | sudo tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null
  apt update
  apt install firefox
#+end_src
* Build emacs
#+begin_src shell :tangle ./2-build-emacs.sh
  mkdir build
  cd build
  wget http://ftp.gnu.org/gnu/emacs/emacs-29.4.tar.xz
  tar -xf emacs-29.4.tar.xz
  cd emacs-29.4
  ./configure --with-wide-int --with-modules --with-native-compilation=aot --with-json --with-tree-sitter --with-gif --with-png --with-jpeg --with-rsvg --with-tiff --with-imagemagick --with-xwidgets CFLAGS="-O2 -pipe -mtune=native -march=native -fomit-frame-pointer"
  make -j $(nproc)
#+end_src
* Install emacs
Separate step only because I don't make myself a sudoer. I'm sure there's a way better way to handle this, I haven't been arsed yet.
#+begin_src shell :tangle ./3-asroot-install-emacs.sh
  cd build/emacs-29.4
  make install
#+end_src
* Post-install
Tangle org files, and set the executable permission for /opt/exwm.sh
#+begin_src shell :tangle ./4-post-install.sh
  emacs --batch --eval "(progn (require 'org) (org-babel-tangle-file \"emacs.org\") (org-babel-tangle-file \"root-tangle.org\") (load-file \"setup.el\") (org-babel-tangle-file \"root-tangle.org\"))"
#+end_src
* Xmodmap
#+begin_src conf :tangle ~/.Xmodmap :mkdirp yes
  clear lock
  remove mod4 = Hyper_L
  add mod3 = Hyper_L Hyper_R

  keycode 66 = Hyper_L
#+end_src
